version: "3.8"

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env

  web:
    build: .
    restart: always
    depends_on: 
      - db
    env_file: ./.env
    volumes:
      - staticfiles:/code/static

  nginx:
    image: nginx:1.21.0
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d/default.conf
